# algorithm config
lr: 0.0001
mini_batch_size: 32
meta_batch_size: 4
num_tasks: 2
num_train_tasks: 2
num_test_tasks: 2
n_epochs: 4000
k_epochs: 5 # optimization epoch
num_stop_conditions: 5
stop_goal: 180
gamma: 0.99
gae_lambda: 0.95
lr_clip_range: 0.2
ent_coef: 0.0001
vf_coef: 0.2
max_grad_norm: 5
norm_inputs: True
norm_outputs: True
norm_adv: True
min_std: 0.5 # e^-20
max_std: 1.5 # e^2

# network config
linear_dim: 128
trans_dim: 256
hidden_dim: 128 
is_recurrent: True
num_rnn_layers: 1
seq_len: 1
is_deterministic: False
layer_normalization: False
# activation: 'tanh'

# n_epochs: 4000
# entropy_method: 'max'
# pg_loss: 'surrogate_clip'
# max_epochs: 256
# init_std: 1
# use_trust_region: False
